# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: pre-commit

on:
  workflow_call:

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  pre-commit:
    name: Detecting code style issues
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v7

      - name: "Detect code style issues"
        uses: j178/prek-action@v2
        with:
          extra-args: ""

      - name: "Generate patch file"
        if: failure()
        run: |
          git diff-index -p HEAD > "${PATCH_FILE}"
          [ -s "${PATCH_FILE}" ] && echo "UPLOAD_PATCH_FILE=${PATCH_FILE}" >> "${GITHUB_ENV}"
        shell: bash
        env:
          PATCH_FILE: pre-commit.patch

      - name: "Upload patch artifact"
        if: failure() && env.UPLOAD_PATCH_FILE != null
        uses: actions/upload-artifact@v7.0.1
        with:
          archive: "false"
          path: ${{ env.UPLOAD_PATCH_FILE }}